#apiVersion: contrail.juniper.net/v1alpha1
#kind: Vrouter
#metadata:
#  labels:
#    contrail_cluster: cluster1
#  name: vrouter1
#  namespace: contrail
apiVersion: contrail.juniper.net/v1alpha1
kind: Cassandra
metadata:
  labels:
    contrail_cluster: cluster1
  name: cassandra1
  namespace: contrail